unit TestClasseSistema;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, SysUtils, Classe.Sistema, Classe;

type
  // Test methods for class TSistema

  TestTSistema = class(TTestCase)
  strict private
    FSistema: TSistema;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestGetNomeTabela;
    procedure TestGetCampoChave;
  end;

implementation

procedure TestTSistema.SetUp;
begin
  FSistema := TSistema.Create;
end;

procedure TestTSistema.TearDown;
begin
  FSistema.Free;
  FSistema := nil;
end;

procedure TestTSistema.TestGetNomeTabela;
var
  ReturnValue: string;
begin
  ReturnValue := FSistema.GetNomeTabela;

  CheckTrue(SameText(ReturnValue, 'SISTEMA'));
end;

procedure TestTSistema.TestGetCampoChave;
var
  ReturnValue: string;
begin
  ReturnValue := FSistema.GetCampoChave;

  CheckTrue(SameText(ReturnValue, 'CODIGO'));
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTSistema.Suite);
end.

