unit TestClasseAbastecimento;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, SysUtils, Classe.Abastecimento, Classe;

type
  TestTAbastecimento = class(TTestCase)
  strict private
    FAbastecimento: TAbastecimento;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestGetNomeTabela;
    procedure TestGetCampoChave;
  end;

implementation

procedure TestTAbastecimento.SetUp;
begin
  FAbastecimento := TAbastecimento.Create;
end;

procedure TestTAbastecimento.TearDown;
begin
  FreeAndNil(FAbastecimento);
end;

procedure TestTAbastecimento.TestGetNomeTabela;
var
  ReturnValue: string;
begin
  ReturnValue := FAbastecimento.GetNomeTabela;

  CheckTrue(SameText(ReturnValue, 'ABASTECIMENTO'));
end;

procedure TestTAbastecimento.TestGetCampoChave;
var
  ReturnValue: string;
begin
  ReturnValue := FAbastecimento.GetCampoChave;

  CheckTrue(SameText(ReturnValue, 'CODIGO'));
end;

initialization
  RegisterTest(TestTAbastecimento.Suite);
end.

