unit TestClasseTanque;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Classe.Tanque, SysUtils, Classe;

type
  // Test methods for class TTanque

  TestTTanque = class(TTestCase)
  strict private
    FTanque: TTanque;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestGetNomeTabela;
    procedure TestGetCampoChave;
  end;

implementation

procedure TestTTanque.SetUp;
begin
  FTanque := TTanque.Create;
end;

procedure TestTTanque.TearDown;
begin
  FTanque.Free;
  FTanque := nil;
end;

procedure TestTTanque.TestGetNomeTabela;
var
  ReturnValue: string;
begin
  ReturnValue := FTanque.GetNomeTabela;

  CheckTrue(SameText(ReturnValue, 'TANQUE'));
end;

procedure TestTTanque.TestGetCampoChave;
var
  ReturnValue: string;
begin
  ReturnValue := FTanque.GetCampoChave;

  CheckTrue(SameText(ReturnValue, 'CODIGO'));
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTTanque.Suite);
end.

